version: '3.9'
services:
  db:
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - nx-practice:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword123
      PGDATA: /var/lib/postgresql/data/data

volumes:
  nx-practice:
